export const Cell = () => <div />
export const Pie = () => <div />
export const PieChart = () => <div />
export const ResponsiveContainer = () => <div />
export const Tooltip = () => <div />
export const Bar = () => <div />
export const BarChart = () => <div />
export const CartesianGrid = () => <div />
export const XAxis = () => <div />
export const YAxis = () => <div />
